name: Publish to npm

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    container: oven/bun
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun i

      - name: Build
        run: bun run build

      - name: Install npm
        uses: actions/setup-node@v4

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
