name: Publish to npm

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Initialize node
        uses: actions/setup-node@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Build
        run: bun run build

      - name: Set up npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_CONFIG_TOKEN }}" > ~/.npmrc

      - name: Publish
        run: npm publish --access public
